### ISSUE TITLE
Move to fastecdsa package

### ISSUE THREAD

**Issue by jcnelson** [blockstack/keylib-py#5]
In developing the performance-sensitive parts of Blockstack CLI, I noticed that the `ecdsa` package is very, very slow.  For example, it takes ~200 milliseconds to convert a private key from WIF format to hexadecimal.  This isn't a problem with `keylib`, but it affects every `keylib` method that uses `ecdsa` to do the heavy lifting.

I've already moved the storage signing/verifying logic in Blockstack CLI over to `fastecdsa` to relive this, with excellent results (~30x speed improvement).  However, it would be good to simply drop `ecdsa` whenever possible from our packages.  For example, the storage logic can't rely many parts of `keylib`.

**Comment by shea256** [comment]
Great idea! 30x - that's pretty insane!

**Comment by jcnelson** [comment]
I can get cracking on this in January.  Will send a PR.

**Comment by jcnelson** [comment]
No longer necessary; we're using cryptography in the places where it needs to be fast.
